# test01
# Electrons

/run/initialize

###################################

# Electrons

/gps/particle e-
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
#/gps/ang/mintheta 0 deg
#/gps/ang/maxtheta 40 deg
#/gps/ang/minphi 130 deg
#/gps/ang/maxphi 200 deg
#/gps/direction 1 0 0
/gps/energy 17 MeV
#/gps/ene/type Gauss
#/gps/ene/mono 13790 keV
#/gps/ene/sigma 20. keV

#/gps/source/list
/run/beamOn 10000
